spring:
  application:
    name: zuul-api-gateway-service
 
server:
  port: 8070
  
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    myapp:
      path: /myapp/**
      service-id: test-sp-app
      